services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Pimcore\Bundle\EcommerceFrameworkBundle\PaymentManager\Payment\PayU:
        arguments:
            $options: []
        tags:
            - { name: pimcore_ecommerce.payment.provider, key: 'payu' }

    Pimcore\Bundle\EcommerceFrameworkBundle\PayU\Installer:
        public: true